export const GET_POST_PAGE = "GET_POST_PAGE";
export const SORT_POSTS_BY_TITLE = "SORT_POSTS_BY_TITLE";
export const SORT_BY_DEFAULT = "SORT_BY_DEFAULT";
export const SEARCH_POST_BY_TITLE = "SEARCH_POST_BY_TITLE";
